# Generated by Django 5.2.7 on 2025-11-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created'], 'verbose_name': 'Critique'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-time_created'], 'verbose_name': 'Ticket'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterModelOptions(
            name='userfollows',
            options={'verbose_name': 'Abonnement'},
        ),
    ]
